product pages added
codevamp-f2fintech/f2fintech-web pull request #24
Opened 2024-07-29 05:13 UTC by tubakhan0415

2024-07-29 05:41 UTC, coder-faraz requested changes
Remove junk files and push the code again

2024-07-29 12:52 UTC, codevamp-technologies requested changes

2024-07-29 12:52 UTC, codevamp-technologies commented on src/components/appBar/Appbar.jsx
> +
discard these changes of Appbar.jsx

2024-07-29 12:52 UTC, codevamp-technologies commented on package.json
> +    "styled-components": "^6.1.12",
do we need this package?

2024-07-31 10:48 UTC, coder-faraz approved these changes
looking fine

2024-07-31 10:49 UTC, merged